#!/usr/bin/env ruby

require_relative "lib/colors"

puts C("list of available commands:", :bold)
puts

Dir[File.join(ENV["HOME"], "git-shell-commands", "*")].each do |file|
  next if File.directory?(file)
  next unless File.executable?(file)

  puts C(File.basename(file), :green, :bold)
end

