#!/usr/bin/env ruby

if ARGV.length != 1
  puts "usage: init <name>"
  puts
  puts "initializes bare git repository"
  exit
end

name = File.basename(ARGV.first, ".git")

path = File.join(ENV["HOME"], "#{name}.git")

puts `git init --bare #{path}`
